### ISSUE TITLE
Recommendation: Yoda Conditions

### ISSUE THREAD

**Issue by sakinshrestha** [BenSibley/Chosen#10]
When doing logical comparisons, use Yoda conditions. For example in `chosen_update_fields()` method in `functions.php`, you have this line of code:

```
 if ( $req == 1 ) {
```

Ideally, that would be:

```
 if ( 1 == $req ) {
```

[Refer to Yoda conditions!](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions)

Also, you could simplify that entire function's code:

```
 if ( $req == 1 ) {
    $label = '*';
} else {
    $label = ' ' . __("optional", "chosen");
}
```

to

```
$label = ( 1 == $req ) ? '*' : ' ' . __( "optional",  "chosen" );
```

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#192
