### ISSUE TITLE
No need to set defaults

### ISSUE THREAD

**Issue by justintadlock** [BenSibley/Chosen#13]
There's really no need to set the defaults when calling `$wp_customize->add_setting()`.  You can remove the `type` (default is already `theme_mod`) and `capability` (default is already `edit_theme_options`) arguments such as in this code:

```
$wp_customize->add_setting( 'excerpt_length', array(
    'default'           => '25',
    'type'              => 'theme_mod',
    'capability'        => 'edit_theme_options',
    'sanitize_callback' => 'absint'
) );
```

It'll save you some code.  Also, look at doing the same when calling `add_control()` or `add_section()` if there are defaults you can remove.

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#189
