### ISSUE TITLE
Use add_query_arg()

### ISSUE THREAD

**Issue by justintadlock** [BenSibley/Chosen#16]
I'd build this link with `add_query_arg()`:

```
'return' => admin_url('themes.php?page=chosen-options')
```

Like so:

```
'return' => add_query_arg( 'page', 'chosen-options', admin_url( 'themes.php' ) )
```

See: https://github.com/BenSibley/Chosen/blob/master/theme-options.php#L15

Also, see: https://github.com/BenSibley/Chosen/blob/master/functions.php#L431

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#186
