### ISSUE TITLE
Resetting theme mods

### ISSUE THREAD

**Issue by justintadlock** [BenSibley/Chosen#19]
The "reset customizer settings" option in the admin is a bit misleading:

> Reset Customizer Settings
> 
> Warning: Clicking this button will erase your current settings in the Customizer.

It doesn't technically erase customizer settings.  What it does is delete the active theme's mods.  Remember that your theme isn't the only thing adding settings to the customizer.  This makes two issues:
- It deletes all settings, even plugin and WP settings (e.g., menus) that use the Theme Mods API.
- It doesn't delete customizer settings that don't use the Theme Mods API.

I think the text should be absolutely clear about what it's doing.  The the reset functionality should also only delete theme-specific mods unless you make it clear to the user that it will delete WP and plugin theme mods.

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#183
