### ISSUE TITLE
No need to escape hard-coded URLs

### ISSUE THREAD

**Issue by justintadlock** [BenSibley/Chosen#22]
The URL in `footer.php` is hardcoded, so it doesn't need to be escaped: https://github.com/BenSibley/Chosen/blob/master/footer.php#L11-L12

```
    $site_url = 'https://www.competethemes.com/chosen/';
    $footer_text = sprintf( __( '<a href="%s">Chosen WordPress Theme</a> by Compete Themes.', 'chosen' ), esc_url( $site_url ) );
```

You just need this:

```
    $footer_text = sprintf( __( '<a href="%s">Chosen WordPress Theme</a> by Compete Themes.', 'chosen' ), 'https://www.competethemes.com/chosen/' );
```

While we're looking at this code, I'd recommend trying to build that internationalized text string in a way that didn't have HTML.  I recommend avoiding HTML in internationalized strings when possible.

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#180
