### ISSUE TITLE
Use the_archive_title/description()

### ISSUE THREAD

**Issue by justintadlock** [BenSibley/Chosen#24]
In `content/archive-header.php`, use the core WP `the_archive_title()` and `the_archive_description()` to output the title and description.  And, if you want to roll something custom, core WP has some filter hooks.

See: 
- https://developer.wordpress.org/reference/functions/the_archive_title/
- https://developer.wordpress.org/reference/functions/the_archive_description/

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#178
