### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by sakinshrestha** [BenSibley/Chosen#5]
Similar code different classes: In `chosen/inc/customizer.php`, the codes in classes `chosen_description_header_image_control, chosen_description_color_control, chosen_description_font_control, chosen_description_display_control_control, chosen_description_footer_text_control and chosen_description_layout_control` have very similar code. You can send the description through as a parameter when calling custom control and make this only one class.

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#197
