### ISSUE TITLE
Enqueue Google Font

### ISSUE THREAD

**Issue by sakinshrestha** [BenSibley/Chosen#6]
When registering and enqueueing scripts in `scripts.php` function `ct_chosen_load_scripts_styles()`, you don't need to call `wp_register_script()` and `wp_enqueue_script()`. Just call `wp_enqueue_script()`.
This:

```
wp_register_style( 'ct-chosen-google-fonts', '//fonts.googleapis.com/css?family=Playfair+Display:400|Raleway:400,700,400italic' );
wp_enqueue_style( 'ct-chosen-google-fonts' );
```

Should be:

```
wp_enqueue_style( 'ct-chosen-google-fonts', '//fonts.googleapis.com/css?family=Playfair+Display:400|Raleway:400,700,400italic' );
```

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#196
