### ISSUE TITLE
Missing Escaping

### ISSUE THREAD

**Issue by sakinshrestha** [BenSibley/Chosen#7]
Escape Missing on following:
- chosen/content-archive.php line 8: `get_permalink()`
- chosen/content/comments-link.php line 7: `get_comments_link()`
- chosen/content/post-categories.php line 19: `get_category_link`
- chosen/functions.php line 195, 265, : `get_permalink()`

**Comment by justintadlock** [comment]
Also need escaping:

Use `esc_attr()` for the value here: https://github.com/BenSibley/Chosen/blob/master/inc/customizer.php#L45

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#195
