### ISSUE TITLE
Pro featured ads in Customizer

### ISSUE THREAD

**Issue by sakinshrestha** [BenSibley/Chosen#9]
You shouldn't bind the user with option disabled. If this option is not there in free version, then it shouldn't be added in. 

In customizer, there are "Header Image, Fonts, Layout, Colors and Display Controls Panels" but they contain no option but a link to a pro plugin. Once the plugin is installed and activated, then only these panels are meaningful. This is not allowed in WordPress.org

**Comment by BenSibley** [comment]
This issue was moved to BenSibley/something#193
